export const mockData = [
  {
    id: 1,
    timePosted: "10h",
    username: "celestgoldberg",
    userComment: "Marvelous picture! ",
    avatar: "https://randomuser.me/api/portraits/women/71.jpg",
    commentLikes: 0,
    children: [],
  },
  {
    id: 2,
    timePosted: "30m",
    username: "applefusion",
    userComment: "Not that much to see over there, come back to NYC :) ",
    avatar: "https://randomuser.me/api/portraits/men/8.jpg",
    commentLikes: 10,
    children: [],
  },
  {
    id: 3,
    timePosted: "45m",
    username: "nicholaswhiney",
    userComment: "OMG <3 <3!!!!!",
    avatar: "https://randomuser.me/api/portraits/men/7.jpg",
    commentLikes: 10,
    children: [],
  },
  {
    id: 4,
    timePosted: "2h",
    username: "lilystokard",
    userComment: "WOW! That is my dream place!",
    avatar: "https://randomuser.me/api/portraits/women/83.jpg",
    commentLikes: 10,
    children: [],
  },
];
